name: NuGet push
on:
  push:
    branches: [ main ]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎
      uses: actions/checkout@v2
    - name: Setup .NET 🐱‍💻
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build 🔧
      run: dotnet build -c Release --no-restore
    - name: Test 🧪
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Publish to NuGet 🚀
      uses: FelixDamrau/publish-nuget@v2.5.6
      with:
        PACKAGE_NAME: 'Develix.AzureDevOps.Connector'
        PROJECT_FILE_PATH: 'src/Core/Core.csproj'
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: 'true'